chain:
    bech32_prefix: cheqd
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - pricefeed
        - slashing
        - staking
        - distribution
        - history
node:
    type: remote
    config:
        rpc:
            client_name: cheqd
            address: ${RPC_ADDRESS}
            max_connections: 20
        grpc:
            address: ${GRPC_ADDRESS} 
            insecure: false
parsing:
    workers: 5
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: true
    average_block_time: 5s
database:
    name: ${DATABASE_NAME}
    host: ${DATABASE_HOST}
    port: ${DATABASE_PORT}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    schema: public
    ssl_mode: require
    max_open_connections: 5
    max_idle_connections: 1
logging:
    level: ${LOG_LEVEL}
    format: json
pricefeed:
    tokens:
        - name: cheq
          units:
               - denom: ncheq
                 exponent: 0
               - denom: cheq
                 exponent: 9
                 price_id: "cheqd-network"
distribution:
    rewards_frequency: 100
