# Goreleaser configuration file

project_name: cheqd-bdjuno

env:
  - GO111MODULE=on

before:
  hooks:
    - make clean
    - go mod tidy -compat=1.17
    - go mod download

builds:
  - id: bdjuno-linux
    main: ./cmd/bdjuno
    binary: bdjuno
    targets:
      - linux_amd64
    ldflags:
      - -X github.com/forbole/juno/v3/cmd.Version={{ .Version }}
	    - -X github.com/forbole/juno/v3/cmd.Commit={{ .Commit }}

archives:
  - id: release-archives
    replacements:
        darwin: Darwin
        linux: Linux
        amd64: x86_64
    format: tar.gz
    wrap_in_directory: true
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  algorithm: sha256

changelog:
  use: github-native
  groups:
  - title: Features
    regexp: "^.*feat[(\\w)]*:+.*$"
    order: 0
  - title: 'Fixes'
    regexp: "^.*fix[(\\w)]*:+.*$"
    order: 1
  - title: 'Performance Improvements'
    regexp: "^.*perf[(\\w)]*:+.*$"
    order: 2
  - title: 'Build Improvements'
    regexp: "^.*build[(\\w)]*:+.*$"
    order: 3
  - title: 'Security'
    regexp: "^.*build[(\\w)]*:+.*$"
    order: 4
  - title: 'Other changes'
    order: 999


release:
  github:
    owner: cheqd
    name: bdjuno
  
  draft: false
  prerelease: true
  mode: append
  header: |
    # Release Notes for {{.ProjectName}} v{{.Version}}
