# Makefile for generating gogoproto-compatible code from proto files

.PHONY: proto-gen proto-install proto-clean

proto-install:
	@echo "Installing protoc-gen-gocosmos..."
	@go install github.com/cosmos/gogoproto/protoc-gen-gocosmos@latest || \
		go install github.com/gogo/protobuf/protoc-gen-gogofaster@latest

proto-gen: proto-install
	@echo "Generating gogoproto-compatible Go code from proto files..."
	@GOMODCACHE=$$(go env GOMODCACHE); \
	COSMOS_SDK=$$GOMODCACHE/github.com/cheqd/cosmos-sdk@v0.50.13-height-mismatch-patched; \
	COSMOS_PROTO=$$GOMODCACHE/github.com/cosmos/cosmos-proto@v1.0.0-beta.5; \
	GOGO_GOOGLEAPIS=$$GOMODCACHE/github.com/gogo/googleapis@v1.4.1; \
	COSMOSSDK_IO=$$GOMODCACHE/cosmossdk.io@v0.50.9; \
	GOGOPROTO=$$GOMODCACHE/github.com/gogo/protobuf@v1.3.2; \
	protoc \
		--proto_path=proto \
		--proto_path=$$COSMOS_SDK/proto \
		--proto_path=$$COSMOS_PROTO/proto \
		--proto_path=$$GOGO_GOOGLEAPIS \
		--proto_path=$$COSMOSSDK_IO/proto \
		--proto_path=$$GOGOPROTO \
		--gocosmos_out=plugins=grpc,Mgogoproto/gogo.proto=github.com/cosmos/gogoproto/gogoproto,Mgoogle/api/annotations.proto=github.com/gogo/googleapis/google/api,paths=source_relative:proto \
		proto/cosmos/mint/v1beta1/query.proto \
		proto/cosmos/mint/v1beta1/mint.proto || \
	protoc \
		--proto_path=proto \
		--proto_path=$$COSMOS_SDK/proto \
		--proto_path=$$COSMOS_PROTO/proto \
		--proto_path=$$GOGO_GOOGLEAPIS \
		--proto_path=$$COSMOSSDK_IO/proto \
		--proto_path=$$GOGOPROTO \
		--gogofaster_out=plugins=grpc,Mgogoproto/gogo.proto=github.com/cosmos/gogoproto/gogoproto,Mgoogle/api/annotations.proto=github.com/gogo/googleapis/google/api,paths=source_relative:proto \
		proto/cosmos/mint/v1beta1/query.proto \
		proto/cosmos/mint/v1beta1/mint.proto
	@echo "IMPORTANT: After generation, comment out init() functions in proto/cosmos/mint/v1beta1/*.pb.go"
	@echo "to prevent duplicate proto type registration. The init() functions that call"
	@echo "proto.RegisterType() and proto.RegisterFile() should be commented out."
	@echo "Proto generation complete. Files are in proto/cosmos/mint/v1beta1/"

proto-clean:
	@rm -rf proto/gen
