chain:
    bech32_prefix: cheqd
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - pricefeed
        - slashing
        - staking
        - distribution
        - actions
node:
    type: remote
    config:
        rpc:
            client_name: cheqd
            address: RPC_ADDRESS
            max_connections: 20
        grpc:
            address: GRPC_ADDRESS
            insecure: false
parsing:
    workers: 5
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: true
    average_block_time: 6s
database:
    name: DATABASE_NAME
    host: DATABASE_HOST
    port: 25060
    user: DATABASE_USER
    password: DATABASE_PASSWORD
    ssl_mode: require
    schema: public
    max_open_connections: 40
    max_idle_connections: 10
    partition_size: 100000
    partition_batch: 1000
logging:
    level: LOG_LEVEL
    format: json
pricefeed:
    tokens:
        - name: cheq
          units:
            - denom: ncheq
              exponent: 0
            - denom: cheq
              exponent: 9
              price_id: cheqd-network
actions:
    port: 3000
