name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:

  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          cache: true

      - name: Test & Create coverage report
        run: make install test-unit stop-docker-test

  build-binary:
    name: "Build Binary"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
          cache: true

      - name: "Install Golang dependencies"
        run: |
          go mod tidy
          make install

      - name: "Build BDJuno binary"
        run: make build
