name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:

  build-bdjuno:
    name: "BDJuno Docker Image"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
          version: latest

      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.digitalocean.com/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=bdjuno-build
            type=sha,format=long

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          load: true
          target: callisto
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/callisto-build.tar
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Upload Docker test image
        uses: actions/upload-artifact@v3
        with:
          name: callisto-build.tar
          path: /tmp/callisto-build.tar

  build-hasuracli:
    name: "Hasura CLI Docker Image"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cheqd/hasuracli

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest

      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.digitalocean.com/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=hasuracli-build
            type=sha,format=long

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.hasura
          platforms: linux/amd64
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/hasuracli-build.tar
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Upload Docker test image
        uses: actions/upload-artifact@v3
        with:
          name: hasuracli-build.tar
          path: /tmp/hasuracli-build.tar
