name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:

  build-docker:
    name: "BDJuno Docker Image"
    runs-on: ubuntu-latest
    env:
      DOCKER_TEST_IMAGE: ${{ github.repository }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          load: true
          target: bdjuno
          tags: ${{ env.DOCKER_TEST_IMAGE }}
          outputs: type=docker,dest=/tmp/bdjuno-image.tar

      - name: Upload Docker test image
        uses: actions/upload-artifact@v3
        with:
          name: bdjuno-image.tar
          path: /tmp/bdjuno-image.tar
