name: "Deploy"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:

  build-docker:
    name: "Deploy to DigitalOcean Container Registry"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest

      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: |
            registry.digitalocean.com/${{ env.IMAGE_NAME }}:${{ secrets.NETWORK_NAME }}-latest
            registry.digitalocean.com/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}
          secrets: |
            "NETWORK_NAME=${{ secrets.NETWORK_NAME }}""


      - name: Push image
        run: |
          docker push registry.digitalocean.com/${{ env.IMAGE_NAME }}:${{ secrets.NETWORK_NAME }}-latest
          docker push registry.digitalocean.com/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}
