name: "Workflow Dispatch"
on: push
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  call-lint:
    name: "Lint"
    uses: cheqd/bdjuno/.github/workflows/lint.yml@chains/cheqd/mainnet
  
  call-test:
    name: "Build & Test"
    uses: cheqd/bdjuno/.github/workflows/build.yml@chains/cheqd/mainnet
