name: "Lint"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:

  sh-euox-pipefail-check:
    name: "Shell pipefail check"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run 'set -euox pipefail' check
        run: bash ./.github/scripts/ensure_set_euox_pipefail.sh

  go-lint:
    # We can't use VALIDATE_GO from super linter because of this issue:
    # https://github.com/github/super-linter/issues/143
    name: "Golang"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

<<<<<<< HEAD
      - uses: actions/setup-go@v4
=======
      - uses: actions/setup-go@v5
>>>>>>> de4cfddd071cda233430244cf8be66765e102114
        with:
          go-version-file: ./go.mod
          cache: false # temporarily off, as golangci-lint doesn't align 100% with cached setup-go@v4, see: https://github.com/golangci/golangci-lint-action/issues/807
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --config .github/linters/.golangci.yaml

  super-lint:
    name: "Super Linter"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to fetch version
      
      - name: Run Super Linter
        uses: github/super-linter/slim@v4
        env:
          IGNORE_GITIGNORED_FILES: true
          DEFAULT_BRANCH: "chains/cheqd/testnet"
          LINTER_RULES_PATH: '.github/linters'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: WARN
          VALIDATE_ALL_CODEBASE: true
          MULTI_STATUS: true

          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSONC: true
          VALIDATE_YAML: true